#!/bin/sh
case "$#" in
0)
	echo 'base: missing input base operand'
	exit 1
	;;
1)
	echo 'base: missing output base operand'
	exit 1
	;;
2)
	while read LINE; do
		echo "obase=$2; ibase=$1; $LINE" | bc
	done
	;;
*)
	echo "obase=$2; ibase=$1; $3" | bc
	;;
esac
exit 0
